services:
  telegram-bot:
    build:
      context: ../..
      dockerfile: apps/defai-telegram-bot/Dockerfile
    container_name: defai-telegram-bot
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    restart: unless-stopped
    ports:
      - "8081:8081"
